include config/best2300a_ibrt/target.mk

#### ANC DEFINE START ######
export ANC_APP ?= 1

#### ANC CONFIG ######
export ANC_FF_ENABLED	?= 1
export ANC_FB_ENABLED	?= 1
export ANC_WNR_ENABLED	?= 0
export AUDIO_ANC_FB_MC ?= 0
export AUDIO_SECTION_SUPPT ?= 1
export AUD_SECTION_STRUCT_VERSION ?= 2
export AUDIO_ANC_FB_MC_HW ?=0
export AUDIO_ANC_FB_ADJ_MC ?=0
##### ANC DEFINE END ######

APP_ANC_TEST ?= 1

TEST_OVER_THE_AIR ?= 1

TOTA ?= 0
OTA_CODE_OFFSET := 0x20000
ifeq ($(ANC_APP),1)
KBUILD_CPPFLAGS += \
    -DANC_APP \
    -D__BT_ANC_KEY__
endif

ifeq ($(ANC_WNR_ENABLED),1)
KBUILD_CPPFLAGS += \
    -DANC_WNR_ENABLED
endif

ifeq ($(USE_CYBERON),1)

export THIRDPARTY_LIB ?= cyberon
KBUILD_CPPFLAGS += -D__CYBERON

export KWS_IN_RAM := 1
ifeq ($(KWS_IN_RAM),1)
CPPFLAGS_${LDS_FILE} += -DKWS_IN_RAM
endif #KWS_IN_RAM

endif #USE_CYBERON

ifeq ($(AUDIO_ANC_FB_ADJ_MC),1)
KBUILD_CPPFLAGS += -DAUDIO_ANC_FB_ADJ_MC
endif


export ANC_ASSIST_ENABLED ?= 0

ifeq ($(ANC_ASSIST_ENABLED), 1)

export ANC_ASSIST_WNR_ENABLED	        	?= 0
export ANC_ASSIST_PILOT_ENABLED	    	    ?= 0
export ANC_ASSIST_NOISE_ADAPTIVE_ENABLED	?= 0
export ANC_ASSIST_HESS_ENABLED	        	?= 0
export ANC_ASSIST_PNC_ENABLED	        	?= 0
export ANC_ASSIST_DEHOWLING_ENABLED		    ?= 0
KBUILD_CPPFLAGS += -D__ANC_ASSIST__
endif



export AF_ANC_CAL_DELAY ?=0
ifeq ($(AF_ANC_CAL_DELAY), 1)
KBUILD_CPPFLAGS += -D__AF_ANC_DUMP_DELAY__
endif