/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Thu May 14 15:30:07 2020. */

#include "current_device_state.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t google_assistant_devices_headphone_v1_CurrentDeviceStatus_fields[4] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, google_assistant_devices_headphone_v1_CurrentDeviceStatus, battery_details, battery_details, &google_assistant_devices_headphone_v1_BatteryDetails_fields),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, google_assistant_devices_headphone_v1_CurrentDeviceStatus, noise_cancellation_level, battery_details, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, google_assistant_devices_headphone_v1_CurrentDeviceStatus, ambient_mode_level, noise_cancellation_level, 0),
    PB_LAST_FIELD
};

const pb_field_t google_assistant_devices_headphone_v1_BatteryDetails_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, google_assistant_devices_headphone_v1_BatteryDetails, remaining_battery_percentage, remaining_battery_percentage, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, google_assistant_devices_headphone_v1_BatteryDetails, connected, remaining_battery_percentage, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, google_assistant_devices_headphone_v1_BatteryDetails, device_type, connected, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(google_assistant_devices_headphone_v1_CurrentDeviceStatus, battery_details[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_google_assistant_devices_headphone_v1_CurrentDeviceStatus_google_assistant_devices_headphone_v1_BatteryDetails)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(google_assistant_devices_headphone_v1_CurrentDeviceStatus, battery_details[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_google_assistant_devices_headphone_v1_CurrentDeviceStatus_google_assistant_devices_headphone_v1_BatteryDetails)
#endif


/* @@protoc_insertion_point(eof) */
