/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Apr 29 15:08:08 2020. */

#include "device_control_request.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t google_assistant_v1_Execution_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, google_assistant_v1_Execution, command, command, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, google_assistant_v1_Execution, params, command, &google_assistant_v1_Execution_ParamsEntry_fields),
    PB_LAST_FIELD
};

const pb_field_t google_assistant_v1_Execution_ParamsEntry_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, google_assistant_v1_Execution_ParamsEntry, key, key, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, google_assistant_v1_Execution_ParamsEntry, value, key, &google_protobuf_Value_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(google_assistant_v1_Execution, params[0]) < 65536 && pb_membersize(google_assistant_v1_Execution_ParamsEntry, value) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_google_assistant_v1_Execution_google_assistant_v1_Execution_ParamsEntry)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(google_assistant_v1_Execution, params[0]) < 256 && pb_membersize(google_assistant_v1_Execution_ParamsEntry, value) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_google_assistant_v1_Execution_google_assistant_v1_Execution_ParamsEntry)
#endif


/* @@protoc_insertion_point(eof) */
